receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s

exporters:
  debug:
    verbosity: detailed

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlphttp/phoenix:
    endpoint: http://phoenix:6006

  otlp/openlit:
    endpoint: openlit:4318
    tls:
      insecure: true

  otlphttp/langfuse:
    endpoint: http://langfuse-web:3000/api/public/otel
    headers:
      Authorization: Basic ${env:LANGFUSE_OTEL_BASIC_AUTH}

  otlp/dash0:
    endpoint: ${env:DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME}:${env:DASH0_ENDPOINT_OTLP_GRPC_PORT}
    headers:
      Authorization: Bearer ${env:DASH0_AUTH_TOKEN}
      Dash0-Dataset: ${env:DASH0_DATASET}

  otlp/dataprepper:
    endpoint: data-prepper:21890
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, otlphttp/phoenix, otlp/openlit, otlphttp/langfuse, otlp/dash0, otlp/dataprepper]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/openlit, otlp/dash0]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/dash0]
